export const SUCCESS_LOGIN = 'LOGIN_SUCCESS';
export const FAIL_PASSWORD_WRONG = 'PASSWORD_WRONG';
export const FAIL_USER_NOT_FOUND = 'USER_NOT_FOUND';

export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const AVAILABLE_EMAIL = 'AVAILABLE_EMAIL';

export const SUCCESS_FAVORITE_DELETED = 'FAVORITE_DELETED';
export const SUCCESS_FAVORITE_UPDATED = 'FAVORITE_UPDATED';

export const USER_CREATED = 'USER_CREATED';
export const DUPLICATED_EMAIL = 'DUPLICATED_EMAIL';

export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';

export const PROFILE_UPDATED = 'PROFILE_UPDATED';

export const PASSWORD_CORRECT = 'PASSWORD_CORRECT';
export const PASSWORD_INCORRECT = 'PASSWORD_INCORRECT';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const PROFILE_DELETED = 'PROFILE_DELETED';
export const IMAGE_UPLOADED = 'IMAGE_UPLOADED';

export const AREA_FETCHED = 'AREA_FETCHED';
export const USER_LOCATION_NOT_FOUND = 'USER_LOCATION_NOT_FOUND';
